### ISSUE TITLE
output.bin

### ISSUE THREAD

**Issue by g3troot** [ZigaMr/ReverseProfanityTool#4]
how to generate output.bin file?

**Comment by ZigaMr** [comment]
Did you run the setup file? Aru you using linux?

**Comment by g3troot** [comment]
> Did you run the setup file? Aru you using linux?

First I install bash setup.sh and then pip install -r requirments.txt
I already tried to work on Kali linux, the latest version of Ubuntu, Windows and WSL Ubuntu in windows. And all without success. This is the last error I encounter anyway in any environment

```
getroot@getroot-VB:~/Downloads/ReverseProfanityTool/seedFileGenerator$ go run main.go 
# command-line-arguments
./main.go:86:42: error: reference to undefined field or method ‘AppendUint32’
   86 |                 buf = binary.LittleEndian.AppendUint32(buf, uint32(seed))
      |                                          ^
./main.go:87:42: error: reference to undefined field or method ‘AppendUint64’
   87 |                 buf = binary.LittleEndian.AppendUint64(buf, key)
      |                                          ^
```
When I run bash setup.sh in ubuntu I get this message at the end. All other dependencies are installed without problems

```
**ERROR: Could not find a version that satisfies the requirement pywin32==306 (from versions: none)
ERROR: No matching distribution found for pywin32==306**
no required module provides package script1.go: go.mod file not found in current directory or any parent directory; see 'go help modules'
setup.sh: line 34: ./script1: No such file or directory
no required module provides package script2.go: go.mod file not found in current directory or any parent directory; see 'go help modules'
setup.sh: line 37: ./script2: No such file or directory
setup.sh: line 40: deactivate: command not found
```

What is the best Linux to use for your project?


secp256k1 library refuses to work in Windows environment

```
D:\ReverseProfanityTool\seedFileGenerator>go run main.go
D:\ReverseProfanityTool\seedFileGenerator <nil>
panic: ScalarMult is not available when secp256k1 is built without cgo

goroutine 9 [running]:
github.com/ethereum/go-ethereum/crypto/secp256k1.(*BitCurve).ScalarMult(...)
        C:/Users/ASUS/go/pkg/mod/github.com/ethereum/go-ethereum@v1.12.0/crypto/secp256k1/scalar_mult_nocgo.go:13
github.com/ethereum/go-ethereum/crypto/secp256k1.(*BitCurve).ScalarBaseMult(...)
        C:/Users/ASUS/go/pkg/mod/github.com/ethereum/go-ethereum@v1.12.0/crypto/secp256k1/curve.go:251
main.PublicKeyFromSeed(0x20a060?)
        D:/ReverseProfanityTool/seedFileGenerator/main.go:53 +0x105
main.genSeedPublicKeysPerCpu(0x0?, 0x30000000, 0x3fffffff, 0x0?)
        D:/ReverseProfanityTool/seedFileGenerator/main.go:85 +0x2cb
created by main.main
        D:/ReverseProfanityTool/seedFileGenerator/main.go:36 +0x187
panic: ScalarMult is not available when secp256k1 is built without cgo

goroutine 6 [running]:
github.com/ethereum/go-ethereum/crypto/secp256k1.(*BitCurve).ScalarMult(...)
        C:/Users/ASUS/go/pkg/mod/github.com/ethereum/go-ethereum@v1.12.0/crypto/secp256k1/scalar_mult_nocgo.go:13
github.com/ethereum/go-ethereum/crypto/secp256k1.(*BitCurve).ScalarBaseMult(...)
        C:/Users/ASUS/go/pkg/mod/github.com/ethereum/go-ethereum@v1.12.0/crypto/secp256k1/curve.go:251
main.PublicKeyFromSeed(0x8a060?)
        D:/ReverseProfanityTool/seedFileGenerator/main.go:53 +0x105
main.genSeedPublicKeysPerCpu(0x0?, 0x0, 0xfffffff, 0x0?)
        D:/ReverseProfanityTool/seedFileGenerator/main.go:85 +0x2cb
created by main.main
        D:/ReverseProfanityTool/seedFileGenerator/main.go:36 +0x187
exit status 2
```

**Comment by ZigaMr** [comment]
I can't recreate the error, make sure you follow the same installation path as in setup file when installing golang dependencies manually.
