### ISSUE TITLE
Very strange error 

### ISSUE THREAD

**Issue by mustquery** [ZigaMr/ReverseProfanityTool#8]
python main.py
Device name: Intel(R) UHD Graphics 630
Device type: ALL | GPU
Device memory: 6491.91015625 MB
Device name: Intel(R) UHD Graphics 630
Device type: ALL | GPU
Device memory: 8114.888671875 MB
Device name: Microsoft Basic Render Driver
Device type: ALL | GPU
Device memory: 8114.888671875 MB
Device name: NVIDIA GeForce GTX 1060
Device type: ALL | GPU
Device memory: 6052.0 MB
Device name: GeForce GTX 1060
Device type: ALL | GPU
Device memory: 6144.0 MB
Choose platform:
[0] <pyopencl.Platform 'Intel(R) OpenCL HD Graphics' at 0x262e2209bc0>
[1] <pyopencl.Platform 'OpenCLOn12' at 0x262e1c58bc0>
[2] <pyopencl.Platform 'NVIDIA CUDA' at 0x262e228a040>
Choice [0]:1
Choose device(s):
[0] <pyopencl.Device 'Intel(R) UHD Graphics 630' on 'OpenCLOn12' at 0x262e2209dd0>
[1] <pyopencl.Device 'Microsoft Basic Render Driver' on 'OpenCLOn12' at 0x262e2209220>
[2] <pyopencl.Device 'NVIDIA GeForce GTX 1060' on 'OpenCLOn12' at 0x262e2209330>
Choice, comma-separated [0]:1
Set the environment variable PYOPENCL_CTX='1:1' to avoid being asked again.
Initializing pubKeys...
_read_8byte_pubkey took 0.854777 seconds
Fetching deployers, contract count:  0
Count of addresses:  1
Number of addresses:  1
Creating buffer elems
Creating buffer precomp
Copying to device elems
Copying to device precomp
Traceback (most recent call last):
  File "D:\programmer\ReverseProfanityTool-main\main.py", line 41, in <module>
    prof.build_kernel()
  File "D:\programmer\ReverseProfanityTool-main\src\tools.py", line 32, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\programmer\ReverseProfanityTool-main\src\tools.py", line 497, in build_kernel
    self.program = cl.Program(self.ctx, kernel).build()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\martv\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopencl\__init__.py", line 534, in build
    self._prg, was_cached = self._build_and_catch_errors(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\martv\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopencl\__init__.py", line 582, in _build_and_catch_errors
    raise err
pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'Microsoft Basic Render Driver' on 'OpenCLOn12' at 0x262e2209220>:

source.cl:481:14: error: program scope variable must reside in constant address space
source.cl:557:33: warning: format specifies type 'unsigned int' but the argument has type 'size_t' (aka 'unsigned long') [-Wformat]
Error executing LLVM compilation action.

(options: -I C:\Users\martv\AppData\Local\Programs\Python\Python311\Lib\site-packages\pyopencl\cl)
(source saved as C:\Users\martv\AppData\Local\Temp\tmp76z98nrs.cl)

**Comment by ghost** [comment]
Hey, I'm getting a similar error: 

Set the environment variable PYOPENCL_CTX='0' to avoid being asked again.
Initializing pubKeys...
_read_8byte_pubkey took 32.301476 seconds
Fetching deployers, contract count:  0
Count of addresses:  0
Number of addresses:  0
Creating buffer elems
Creating buffer precomp
Copying to device elems
Copying to device precomp
UNSUPPORTED (log once): buildComputeProgram: cl2Metal failed
Traceback (most recent call last):
  File "/Users/User1/ReverseProfanityTool-main/main.py", line 36, in <module>
    prof.build_kernel()
  File "/Users/User/ReverseProfanityTool-main/src/tools.py", line 32, in wrapper
    result = func(*args, **kwargs)
  File "/Users/User1/ReverseProfanityTool-main/src/tools.py", line 498, in build_kernel
    self.program = cl.Program(self.ctx, kernel).build()
  File "/Users/User1/ReverseProfanityTool-main/myenv_new/lib/python3.10/site-packages/pyopencl/__init__.py", line 534, in build
    self._prg, was_cached = self._build_and_catch_errors(
  File "/Users/User1/ReverseProfanityTool-main/myenv_new/lib/python3.10/site-packages/pyopencl/__init__.py", line 582, in _build_and_catch_errors
    raise err
pyopencl._cl.RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE - clBuildProgram failed: BUILD_PROGRAM_FAILURE

Build on <pyopencl.Device 'Apple M1 Pro' on 'Apple' at 0x1027f00>:

program_source:481:14: error: program scope variable must reside in constant address space
__global int counter = 0;
             ^
program_source:557:33: warning: format specifies type 'unsigned int' but the argument has type 'size_t' (aka 'unsigned long')
            printf("ID: %u \n", id);
                        ~~      ^~
                        %zu



Any advice or help would be greatly appreciated!
